version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/postgres/data:/var/lib/postgresql/data

  springboot-gateway:
    build: ./backend/springboot/ux_beta
    ports:
      - "8080:8080"
    depends_on:
      - fastapi-llm
      - fastapi-vision
      - postgres

  fastapi-llm:
    build: ./backend/fastapi_llm
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  fastapi-vision:
    build: ./backend/fastapi_vision
    ports:
      - "5001:5001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
